"""update quote and invoice hybrid schema

Revision ID: 6438344d3a19
Revises: 
Create Date: 2026-04-18 21:00:46.183249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6438344d3a19'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('source_quote_id', sa.Integer(), nullable=True))
    op.add_column('invoices', sa.Column('total_amount', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('status', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('is_finalized', sa.Boolean(), nullable=True))
    op.add_column('invoices', sa.Column('invoice_data', sa.JSON(), nullable=True))
    op.add_column('invoices', sa.Column('final_pdf_path', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('invoices', sa.Column('invoice_number', sa.String(), nullable=True))
    op.create_index(op.f('ix_invoices_created_at'), 'invoices', ['created_at'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_foreign_key(None, 'invoices', 'quotes', ['source_quote_id'], ['id'])
    op.drop_column('invoices', 'client_invoice_pdf')
    op.add_column('quotes', sa.Column('total_amount', sa.Float(), nullable=True))
    op.add_column('quotes', sa.Column('status', sa.String(), nullable=True))
    op.add_column('quotes', sa.Column('quote_data', sa.JSON(), nullable=True))
    op.add_column('quotes', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('quotes', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('quotes', sa.Column('cached_pdf_path', sa.String(), nullable=True))
    op.drop_column('quotes', 'client_quote_pdf')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('client_quote_pdf', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('quotes', 'cached_pdf_path')
    op.drop_column('quotes', 'updated_at')
    op.drop_column('quotes', 'created_at')
    op.drop_column('quotes', 'quote_data')
    op.drop_column('quotes', 'status')
    op.drop_column('quotes', 'total_amount')
    op.add_column('invoices', sa.Column('client_invoice_pdf', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_invoices_inovoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_created_at'), table_name='invoices')
    op.drop_column('invoices', 'inovoice_number')
    op.drop_column('invoices', 'created_at')
    op.drop_column('invoices', 'final_pdf_path')
    op.drop_column('invoices', 'invoice_data')
    op.drop_column('invoices', 'is_finalized')
    op.drop_column('invoices', 'status')
    op.drop_column('invoices', 'total_amount')
    op.drop_column('invoices', 'source_quote_id')
    # ### end Alembic commands ###
